package contracts

// NOTE: This file was automatically generated.

// Instances of AvailabilityData represent the result of executing an
// availability test.
type AvailabilityData struct {
	Domain

	// Schema version
	Ver int `json:"ver"`

	// Identifier of a test run. Use it to correlate steps of test run and
	// telemetry generated by the service.
	Id string `json:"id"`

	// Name of the test that these availability results represent.
	Name string `json:"name"`

	// Duration in format: DD.HH:MM:SS.MMMMMM. Must be less than 1000 days.
	Duration string `json:"duration"`

	// Success flag.
	Success bool `json:"success"`

	// Name of the location where the test was run from.
	RunLocation string `json:"runLocation"`

	// Diagnostic message for the result.
	Message string `json:"message"`

	// Collection of custom properties.
	Properties map[string]string `json:"properties,omitempty"`

	// Collection of custom measurements.
	Measurements map[string]float64 `json:"measurements,omitempty"`
}

// Returns the name used when this is embedded within an Envelope container.
func (data *AvailabilityData) EnvelopeName() string {
	return "Microsoft.ApplicationInsights.Availability"
}

// Returns the base type when placed within a Data object container.
func (data *AvailabilityData) BaseType() string {
	return "AvailabilityData"
}

// Creates a new AvailabilityData instance with default values set by the schema.
func NewAvailabilityData() *AvailabilityData {
	return &AvailabilityData{
		Ver:          2,
		Properties:   make(map[string]string),
		Measurements: make(map[string]float64),
	}
}
